# Generated by Django 4.0.5 on 2022-06-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_message_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Your Subject', max_length=255),
        ),
    ]
